# Generated by Django 2.0.5 on 2018-05-16 19:45

from django.db import migrations, models
import django.db.models.deletion
import list_of_books.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('number_of_pages', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image_file', models.ImageField(default='', upload_to=list_of_books.models.content_file_name)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='type_of_book',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='list_of_books.Type'),
        ),
    ]
