# Generated by Django 2.0.5 on 2018-05-22 06:17

from django.db import migrations, models
import django.utils.timezone
import list_of_books.models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_books', '0002_auto_20180522_0459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-createDate']},
        ),
        migrations.AddField(
            model_name='book',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='image_file',
            field=models.ImageField(default='', upload_to=list_of_books.models.content_file_name),
        ),
    ]
